### ISSUE TITLE
install from pip? or aptget? can not found it 

### ISSUE THREAD

**Issue by lucasjinreal** [eric-wieser/ros_numpy#12]

**Comment by eric-wieser** [comment]
This is (was?) distributed via the ros apt repositories. It didn't make sense to distribute on pip since it depends on ros which is not on PIP.

See this question: http://answers.ros.org/question/270439/ros_numpy-package/

**Comment by asimonov-hitachi** [comment]
@eric-wieser, i am working with Indigo (because of the client...), but use python3 (for tensorflow and the like). 
so have to pull a few packages from default indigo distribution into python3 setting. 
also the version of ros_numpy in indigo is very old.
for example, right now i am trying to use it to get images from FLIR but getting 'TypeError: Unrecognized encoding bayer_rggb8'
looks like this was added later to ros_numpy, but it is not in apt installed ros-indigo-ros-numpy version.

so, to make story short - i need instructions how to install ros_numpy into python3 under indigo. 
what is the best way?
pull ros_numpy into my workspace?
or just copy files next to my project files and add to pythonpath?

sorry about this, but apt on indigo is now not a viable way for many people

**Comment by asimonov-hitachi** [comment]
actually, just dropping the ros_numpy package into the workspace works fine
